### ISSUE TITLE
Is this crate maintained?

### ISSUE THREAD

**Issue by matthiasbeyer** [hjson/hjson-rust#25]
Asking because dependencies are outdated and there seems to be [little progress overall](https://github.com/hjson/hjson-rust/pulse/monthly).

@dqsully ?

**Comment by MillieSilva** [comment]
I would also like to know @dqsully @laktak

**Comment by matthiasbeyer** [comment]
I guess after over one year we can safely say: No, it is not.

**Comment by laktak** [comment]
Sorry, didn't see this. If you or someone else would like to take over as a maintainer please let us know.

**Comment by richardwesthaver** [comment]
just an FYI the readme links to hjson.org should be updated to https://hjson.github.io/ - i didn’t check who owns that domain currently but it’s not related to the data format for sure

**Comment by tishun** [comment]
> Sorry, didn't see this. If you or someone else would like to take over as a maintainer please let us know.

@laktak I can spare a few hours monthly for this if you still need help?

**Comment by laktak** [comment]
@tishun  -  @dqsully and @trobro  have taken over as maintainers.

**Comment by trobro** [comment]
@richardwesthaver I cannot find any reference to hsjon.org in this repository. There was a commit in 2020 to change all URLs. Are you talking about some uploaded release rather than the latest master branch?

**Comment by tishun** [comment]
I was kind of hoping to ramp up with Rust helping with this project. I also saw the topic about Rust upgrade and it seems to be a blocker for some of the issues. I could educate myself some more and suggest a solution?

**Comment by trobro** [comment]
Sounds good!

**Comment by Dzordzu** [comment]
Just submitted some PRs that solve some of the opened issues and drop old dependencies. They are quite simple, looking at them should take up to 15min and would close at least 5 issues. 

NOTE: I'm not willing to become a regular maintainer, but I can look for this repo from time to time

**Comment by trobro** [comment]
Thanks @Dzordzu, appreciated!

**Comment by Dzordzu** [comment]
Who does have rights to the crates.io? I see @dqsully and @laktak. Can anyone publish a new version?

**Comment by trobro** [comment]
@Dzordzu I've asked them to add me too, will then publish.

**Comment by Dzordzu** [comment]
Thanks a lot!

**Comment by trobro** [comment]
v1.0.0 is available on crates.io now. I can do future releases if needed, so closing this issue.
