### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [hjson/hjson-rust#3]
Serde 0.9.0 release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0
Serde 1.0.0 release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by jkcclemens** [comment]
@laktak Any information on the status of this?

**Comment by laktak** [comment]
@jkcclemens this will probably take a while. PRs are welcome if there are any takers.

**Comment by laktak** [comment]
I'll close this issue in favor of #6
